### ISSUE TITLE
Updating Twitter icon

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [mohammadshaad/mohammadshaad.github.io#16]
Your portfolio website has an old Twitter icon, i.e., the "bird" logo. It should be changed to the "X" logo.

![Screenshot 2023-10-22 173313](https://github.com/mohammadshaad/mohammadshaad.github.io/assets/133518394/b5501ebc-fa5d-4fca-97f8-200f045410ba)

**Comment by mohammadshaad** [comment]
Okay boss

**Comment by mohammadshaad** [comment]
Feel free to make the PR
